### ISSUE TITLE
read_file in list context returns undef when in err_mode carp

### ISSUE THREAD

**Issue by genio** [perhunter/slurp#4]
Here's a test script:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use IO::Handle ();
use v5.10;

use Data::Dumper qw(Dumper);
use File::Spec ();
use File::Slurp qw(read_file);

my @data;

# pick a bad file so we are sure to error out
my $file=File::Spec->catfile(File::Spec->tmpdir, "foo", "bar", "baz");

my $err = do {
    local $@;
    eval {
        @data = read_file($file, {err_mode=>"carp"});
        1;
    };
    $@;
};

say $err; # nothing in here. we're sending errors to warn
say Dumper @data;
```

It results in:

```
read_file '/tmp/foo/bar/baz' - sysopen: No such file or directory at foo.t line 19.

$VAR1 = undef;
```

When it _should_ just:

```
read_file '/tmp/foo/bar/baz' - sysopen: No such file or directory at foo.t line 19.

```

The `read_file` function fails here:
```perl
@_ = ( $opts, "read_file '$file_name' - sysopen: $!");
goto &_error ;
```

In `_error`, when the fail mode is `quiet` it just does a `return`. When in `croak` mode, it dies. When in `carp` mode, it falls all the way through to the end and does `return undef`. That undef, in list context, gets added as the first entry to the returning data. This should be just a `return`.

**Comment by genio** [comment]
Can't change this broken functionality.

**Comment by perhunter** [comment]
On 10/02/2018 08:54 PM, Chase Whitener wrote:
>
> Here's a test script:
>
> #!/usr/bin/env perl
> use  strict;
> use  warnings;
> use  IO::Handle ();
> use  v5.10;
>
> use  Data::Dumperqw(Dumper);
> use  File::Spec ();
> use  File::Slurpqw(read_file);
>
> my  @data;
>
> # pick a bad file so we are sure to error out
> my  $file=File::Spec->catfile(File::Spec->tmpdir,"foo","bar","baz");
>
> my  $err  =do  {
>      local  $@;
>      eval  {
>          @data  = read_file($file, {err_mode=>"carp"});
>          1;
>      };
>      $@;
> };
>
> say  $err;# nothing in here. we're sending errors to warn
> say  Dumper@data;
>
> It results in:
>
> |read_file '/tmp/foo/bar/baz' - sysopen: No such file or directory at 
> foo.t line 19. $VAR1 = undef; |
>
> When it /should/ just:
>
> |read_file '/tmp/foo/bar/baz' - sysopen: No such file or directory at 
> foo.t line 19. |
>
> The |read_file| function fails here:
>
> @_  = ($opts,"read_file '$file_name' - sysopen: $!");
> goto  &_error ;
>
> In |_error|, when the fail mode is |quiet| it just does a |return|. 
> When in |croak| mode, it dies. When in |carp| mode, it falls all the 
> way through to the end and does |return undef|. That undef, in list 
> context, gets added as the first entry to the returning data. This 
> should be just a |return|.
>
>

very interesting. i have always advocated plain return over return undef 
for that very reason! plain return works correctly for scalar and list 
contexts. the argument against it is always something like calling a sub 
in a list context and expecting a scalar value (to fill an arg or hash 
list value). the proper solution is for the caller to use scalar() to 
make sure they get a scalar when they need one. returning undef breaks 
the other case (empty list vs a single value) and can't be fixed by the 
caller.

in any case, this test is good and should be fixed in the module.

i do intend to read up on the other patches. is there any easy way to 
see them all? just scan RT or what?

i have been out of the loop with life and lack of work issues. i hope to 
be able to put some energy (if only doing reviews and such) back to 
slurp. i appreciate all the work being done to it.

thanx,

uri
